version: '3.6'

services:
  database:
    container_name: ctf-bot-db
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: ctf-bot-db
    ports:
      - 5432:5432
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    restart: unless-stopped

volumes:
  database:
